<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="DESKTOP-NH0EPD3" name="TracksPageScripts.Linkedin_SignUp_PageScripts" tests="11" failures="2" timestamp="15 Jun 2018 21:31:19 GMT" time="49.594" errors="0">
  <testcase name="firstTestCase" time="7.293" classname="TracksPageScripts.Linkedin_SignUp_PageScripts"/>
  <testcase name="secondTestCase" time="4.377" classname="TracksPageScripts.Linkedin_SignUp_PageScripts"/>
  <testcase name="thirdTestCase" time="4.221" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Please enter your email address] but found [Please enter your email address or mobile number]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Please enter your email address] but found [Please enter your email address or mobile number]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TracksPageScripts.Linkedin_SignUp_PageScripts.thirdTestCase(Linkedin_SignUp_PageScripts.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- thirdTestCase -->
  <testcase name="thirdTestCase" time="4.156" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
    <skipped/>
  </testcase> <!-- thirdTestCase -->
  <testcase name="thirdTestCase" time="4.264" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
    <skipped/>
  </testcase> <!-- thirdTestCase -->
  <testcase name="thirdTestCase" time="4.200" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
    <skipped/>
  </testcase> <!-- thirdTestCase -->
  <testcase name="fourthTestCase" time="4.185" classname="TracksPageScripts.Linkedin_SignUp_PageScripts"/>
  <testcase name="fifthTestCase" time="4.283" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
    <skipped/>
  </testcase> <!-- fifthTestCase -->
  <testcase name="fifthTestCase" time="4.039" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Please enter a valid email address] but found [Please enter a valid email address or mobile number]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Please enter a valid email address] but found [Please enter a valid email address or mobile number]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TracksPageScripts.Linkedin_SignUp_PageScripts.fifthTestCase(Linkedin_SignUp_PageScripts.java:169)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- fifthTestCase -->
  <testcase name="fifthTestCase" time="4.385" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
    <skipped/>
  </testcase> <!-- fifthTestCase -->
  <testcase name="fifthTestCase" time="4.191" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
    <skipped/>
  </testcase> <!-- fifthTestCase -->
</testsuite> <!-- TracksPageScripts.Linkedin_SignUp_PageScripts -->
